### ISSUE TITLE
The application has stopped

### ISSUE THREAD

**Issue by marmistrz** [dbjorge/AirPush-Detector#6] opened 2016-07-31 10:32 UTC
Using AirPush Detector on Samsung Galaxy J7 2016. The applications halts when scanning app 157.

**Comment by dbjorge** [comment] 2016-09-04 19:02
The root cause is that the getPackageInfo call at https://github.com/dbjorge/AirPush-Detector/blob/master/src/com/brosmike/airpushdetector/Detector.java#L215 fails if too much information is returned (typical on newer phones with many apps pre-installed). This could probably be fixed by using fewer flags on that call and performing separate calls to enumerate the apps installed vs enumerating the activities/receivers/etc for each of them.

That said: AirPush Detector has been obsolete for years, and even if it were to be fixed, I'm sure its heuristics are very outdated (the ad companies used to take a few months to work around whatever heuristic was being used at the time). I'm not going to be fixing this (or updating this app further, in general) because it is obsolete on all modern phones and I don't have the time to continue an arms race with the ad companies.

**Closed as completed by dbjorge** 2016-09-04 19:02 UTC
